In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/superstore.csv", encoding="latin1")

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
df.shape

(9994, 21)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df["Order ID"].nunique()

5009

In [8]:
df["Customer ID"].nunique()

793

In [9]:
id="x7c4pz"
df["Order Date"].head()

0     11/8/2016
1     11/8/2016
2     6/12/2016
3    10/11/2015
4    10/11/2015
Name: Order Date, dtype: str

In [10]:
df["Order Date"].min(), df["Order Date"].max()

('1/1/2017', '9/9/2017')

In [11]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%m/%d/%Y"
)
df["Order Date"].dtype

dtype('<M8[us]')

In [12]:
df["Order Date"].min(), df["Order Date"].max()

(Timestamp('2014-01-03 00:00:00'), Timestamp('2017-12-30 00:00:00'))

In [13]:
# Convert the Ship Date column from text (string) to a proper datetime format
df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%m/%d/%Y"
)
# Check the data types of Order Date and Ship Date
# Both should now be datetime types
df[["Order Date", "Ship Date"]].dtypes

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [14]:
# Generate summary statistics for the main numerical business columns
# This helps us understand their typical values and spot unusual values
df[["Sales", "Quantity", "Discount", "Profit"]].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [15]:
# Check how many unique values exist in the main categorical columns
# This helps us understand the different business segments in the dataset
df[["Category", "Sub-Category", "Region", "Segment", "Ship Mode"]].nunique()

Category         3
Sub-Category    17
Region           4
Segment          3
Ship Mode        4
dtype: int64

In [16]:
# Display the unique values in the main categorical columns
# This helps us check for spelling differences, unexpected labels, or inconsistent categories

for column in ["Category", "Sub-Category", "Region", "Segment", "Ship Mode"]:
    print(f"\n{column}:")
    print(df[column].unique())

Category:
<StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

Sub-Category:
<StringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

Region:
<StringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str

Segment:
<StringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

Ship Mode:
<StringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

In [17]:
# Negative profit values are important because they may reveal
# products or sales situations that are hurting business performance

loss_making_rows = (df["Profit"] < 0).sum()

print("Number of loss-making order lines:", loss_making_rows)

Number of loss-making order lines: 1871

In [18]:
# Calculate the number of loss-making order lines in each product category
# This helps us identify which major category has the most frequent losses

loss_by_category = (
    df[df["Profit"] < 0]
    .groupby("Category")
    .size()
    .sort_values(ascending=False)
)

print(loss_by_category)

Category
Office Supplies    886
Furniture          714
Technology         271
dtype: int64

In [19]:
# Calculate the total profit from loss-making transactions for each category
# Since these values are negative, they represent the total financial loss

loss_amount_by_category = (
    df[df["Profit"] < 0]
    .groupby("Category")["Profit"]
    .sum()
    .sort_values()
)

print(loss_amount_by_category)

Category
Furniture         -60936.1090
Office Supplies   -56615.2585
Technology        -38579.9182
Name: Profit, dtype: float64

In [20]:
# Calculate total Sales and Profit for each product category
# This lets us compare revenue generation with actual profitability

category_performance = (
    df.groupby("Category")[["Sales", "Profit"]]
    .sum()
    .sort_values("Sales", ascending=False)
)

print(category_performance)

                       Sales       Profit
Category
Technology       836154.0330  145454.9481
Furniture        741999.7953   18451.2728
Office Supplies  719047.0320  122490.8008

In [21]:
# Calculate total Sales and Profit for each sub-category
# This helps us identify the strongest and weakest product groups

subcategory_performance = (
    df.groupby("Sub-Category")[["Sales", "Profit"]]
    .sum()
    .sort_values("Sales", ascending=False)
)

print(subcategory_performance)

                    Sales      Profit
Sub-Category
Phones        330007.0540  44515.7306
Chairs        328449.1030  26590.1663
Storage       223843.6080  21278.8264
Tables        206965.5320 -17725.4811
Binders       203412.7330  30221.7633
Machines      189238.6310   3384.7569
Accessories   167380.3180  41936.6357
Copiers       149528.0300  55617.8249
Bookcases     114879.9963  -3472.5560
Appliances    107532.1610  18138.0054
Furnishings    91705.1640  13059.1436
Paper          78479.2060  34053.5693
Supplies       46673.5380  -1189.0995
Art            27118.7920   6527.7870
Envelopes      16476.4020   6964.1767
Labels         12486.3120   5546.2540
Fasteners       3024.2800    949.5182

In [22]:
# Calculate total Sales and Profit for each region
# This helps us compare business performance across different geographic areas

region_performance = (
    df.groupby("Region")[["Sales", "Profit"]]
    .sum()
    .sort_values("Sales", ascending=False)
)

print(region_performance)

               Sales       Profit
Region
West     725457.8245  108418.4489
East     678781.2400   91522.7800
Central  501239.8908   39706.3625
South    391721.9050   46749.4303

In [23]:
# Calculate total Sales and Profit for each customer segment
# This helps us understand which type of customer contributes most to business performance

segment_performance = (
    df.groupby("Segment")[["Sales", "Profit"]]
    .sum()
    .sort_values("Sales", ascending=False)
)

print(segment_performance)

                    Sales       Profit
Segment
Consumer     1.161401e+06  134119.2092
Corporate    7.061464e+05   91979.1340
Home Office  4.296531e+05   60298.6785

In [24]:
# Extract the year from Order Date
# We need this to compare business performance across different years

df["Year"] = df["Order Date"].dt.year

# Calculate total Sales and Profit for each year
# This helps us identify whether the business is growing or declining over time

yearly_performance = (
    df.groupby("Year")[["Sales", "Profit"]]
    .sum()
    .sort_index()
)

print(yearly_performance)

            Sales      Profit
Year
2014  484247.4981  49543.9741
2015  470532.5090  61618.6037
2016  609205.5980  81795.1743
2017  733215.2552  93439.2696

In [25]:
# Create a Month column from Order Date
# Using the month period lets us group all transactions belonging to the same month

df["Month"] = df["Order Date"].dt.to_period("M")

# Calculate total Sales and Profit for each month
# This helps us identify growth patterns, seasonal peaks, and weaker periods

monthly_performance = (
    df.groupby("Month")[["Sales", "Profit"]]
    .sum()
    .sort_index()
)

print(monthly_performance)

               Sales      Profit
Month
2014-01   14236.8950   2450.1907
2014-02    4519.8920    862.3084
2014-03   55691.0090    498.7299
2014-04   28295.3450   3488.8352
2014-05   23648.2870   2738.7096
2014-06   34595.1276   4976.5244
2014-07   33946.3930   -841.4826
2014-08   27909.4685   5318.1050
2014-09   81777.3508   8328.0994
2014-10   31453.3930   3448.2573
2014-11   78628.7167   9292.1269
2014-12   69545.6205   8983.5699
2015-01   18174.0756  -3281.0070
2015-02   11951.4110   2813.8508
2015-03   38726.2520   9732.0978
2015-04   34195.2085   4187.4962
2015-05   30131.6865   4667.8690
2015-06   24797.2920   3335.5572
2015-07   28765.3250   3288.6483
2015-08   36898.3322   5355.8084
2015-09   64595.9180   8209.1627
2015-10   31404.9235   2817.3660
2015-11   75972.5635  12474.7884
2015-12   74919.5212   8016.9659
2016-01   18542.4910   2824.8233
2016-02   22978.8150   5004.5795
2016-03   51715.8750   3611.9680
2016-04   38750.0390   2977.8149
2016-05   56987.7280   8662.1464
2016-06   40344.5340   4750.3781
2016-07   39261.9630   4432.8779
2016-08   31115.3743   2062.0693
2016-09   73410.0249   9328.6576
2016-10   59687.7450  16243.1425
2016-11   79411.9658   4011.4075
2016-12   96999.0430  17885.3093
2017-01   43971.3740   7140.4391
2017-02   20301.1334   1613.8720
2017-03   58872.3528  14751.8915
2017-04   36521.5361    933.2900
2017-05   44261.1102   6342.5828
2017-06   52981.7257   8223.3357
2017-07   45264.4160   6952.6212
2017-08   63120.8880   9040.9557
2017-09   87866.6520  10991.5556
2017-10   77776.9232   9275.2755
2017-11  118447.8250   9690.1037
2017-12   83829.3188   8483.3468

In [26]:
# Calculate total Sales for each individual product
# This helps us identify the products generating the most revenue

product_sales = (
    df.groupby("Product Name")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

# Display the top 10 products by total Sales
print(product_sales.head(10))

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

In [27]:
# Calculate total Profit for each individual product
# This helps us identify the products that contribute the most profit

product_profit = (
    df.groupby("Product Name")["Profit"]
    .sum()
    .sort_values(ascending=False)
)

# Display the top 10 most profitable products
print(product_profit.head(10))

Product Name
Canon imageCLASS 2200 Advanced Copier                                          25199.9280
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     7753.0390
Hewlett Packard LaserJet 3310 Copier                                            6983.8836
Canon PC1060 Personal Laser Copier                                              4570.9347
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       4094.9766
Ativa V4110MDD Micro-Cut Shredder                                               3772.9461
3D Systems Cube Printer, 2nd Generation, Magenta                                3717.9714
Plantronics Savi W720 Multi-Device Wireless Headset System                      3696.2820
Ibico EPK-21 Electric Binding System                                            3345.2823
Zebra ZM400 Thermal Label Printer                                               3343.5360
Name: Profit, dtype: float64

In [28]:
# Calculate the total Profit generated by each individual product
# Sorting in ascending order puts the products with the biggest losses first

product_loss = (
    df.groupby("Product Name")["Profit"]
    .sum()
    .sort_values()
)

# Display the 10 products with the lowest total profit
# Negative values indicate that the product generated an overall loss

print(product_loss.head(10))

Product Name
Cubify CubeX 3D Printer Double Head Print                           -8879.9704
Lexmark MX611dhe Monochrome Laser Printer                           -4589.9730
Cubify CubeX 3D Printer Triple Head Print                           -3839.9904
Chromcraft Bull-Nose Wood Oval Conference Tables & Bases            -2876.1156
Bush Advantage Collection Racetrack Conference Table                -1934.3976
GBC DocuBind P400 Electric Binding System                           -1878.1662
Cisco TelePresence System EX90 Videoconferencing Unit               -1811.0784
Martin Yale Chadless Opener Electric Letter Opener                  -1299.1836
Balt Solid Wood Round Tables                                        -1201.0581
BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables   -1148.4375
Name: Profit, dtype: float64

In [29]:
# Calculate the average Profit for each Discount level
# This helps us investigate whether higher discounts are associated with lower profitability

discount_profit = (
    df.groupby("Discount")["Profit"]
    .agg(["mean", "sum", "count"])
    .sort_index()
)

print(discount_profit)

                mean          sum  count
Discount
0.00       66.900292  320987.6032   4798
0.10       96.055074    9029.1770     94
0.15       27.288298    1418.9915     52
0.20       24.702572   90337.3060   3657
0.30      -45.679636  -10369.2774    227
0.32      -88.560656   -2391.1377     27
0.40     -111.927429  -23057.0504    206
0.45     -226.646464   -2493.1111     11
0.50     -310.703456  -20506.4281     66
0.60      -43.077212   -5944.6552    138
0.70      -95.874060  -40075.3569    418
0.80     -101.796797  -30539.0392    300

In [30]:
# Check whether Sales or Quantity contains zero or negative values
# These checks help identify records that may need further investigation

invalid_sales = (df["Sales"] <= 0).sum()
invalid_quantity = (df["Quantity"] <= 0).sum()

print("Sales values <= 0:", invalid_sales)
print("Quantity values <= 0:", invalid_quantity)

Sales values <= 0: 0
Quantity values <= 0: 0

In [31]:
# Compare Order Date and Ship Date for every order line
# A valid shipment date should be the same as or later than the order date

invalid_ship_dates = (
    df["Ship Date"] < df["Order Date"]
).sum()

print("Ship dates earlier than order dates:", invalid_ship_dates)

Ship dates earlier than order dates: 0

In [32]:
# Calculate the key business metrics for the entire dataset
# These metrics will later become the main KPI cards in our Power BI dashboard

total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
total_quantity = df["Quantity"].sum()
total_orders = df["Order ID"].nunique()
total_customers = df["Customer ID"].nunique()

print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Total Quantity Sold:", total_quantity)
print("Total Orders:", total_orders)
print("Total Customers:", total_customers)

Total Sales: 2297200.8603
Total Profit: 286397.0217
Total Quantity Sold: 37873
Total Orders: 5009
Total Customers: 793

In [33]:
# Calculate the overall profit margin
# Profit margin shows what percentage of Sales is retained as Profit

profit_margin = (total_profit / total_sales) * 100

print("Overall Profit Margin:", profit_margin, "%")

Overall Profit Margin: 12.467217240315605 %

In [34]:
# Calculate Sales and Profit for each region
# We will use these values to calculate the profit margin for each region

region_metrics = (
    df.groupby("Region")[["Sales", "Profit"]]
    .sum()
)

# Calculate the percentage of Sales that becomes Profit in each region
region_metrics["Profit Margin (%)"] = (
    region_metrics["Profit"] / region_metrics["Sales"]
) * 100

# Sort regions by profit margin from highest to lowest
region_metrics = region_metrics.sort_values(
    "Profit Margin (%)",
    ascending=False
)

print(region_metrics)

               Sales       Profit  Profit Margin (%)
Region
West     725457.8245  108418.4489          14.944831
East     678781.2400   91522.7800          13.483399
South    391721.9050   46749.4303          11.934342
Central  501239.8908   39706.3625           7.921629

In [35]:
# Calculate Sales and Profit for each region
# We will use these values to calculate the profit margin for each region

region_metrics = (
    df.groupby("Region")[["Sales", "Profit"]]
    .sum()
)

# Calculate the percentage of Sales that becomes Profit in each region
region_metrics["Profit Margin (%)"] = (
    region_metrics["Profit"] / region_metrics["Sales"]
) * 100

# Sort regions by profit margin from highest to lowest
region_metrics = region_metrics.sort_values(
    "Profit Margin (%)",
    ascending=False
)

print(region_metrics)

               Sales       Profit  Profit Margin (%)
Region
West     725457.8245  108418.4489          14.944831
East     678781.2400   91522.7800          13.483399
South    391721.9050   46749.4303          11.934342
Central  501239.8908   39706.3625           7.921629

In [36]:
# Calculate total Profit for each product category
# Sorting from highest to lowest helps us identify the most profitable categories

category_profit = (
    df.groupby("Category")["Profit"]
    .sum()
    .sort_values(ascending=False)
)

print(category_profit)

Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64

In [37]:
# Calculate total Sales and total Profit for each product category
# This helps us compare how much each category sells and how much profit it generates

category_summary = (
    df.groupby("Category")[["Sales", "Profit"]]
    .sum()
    .sort_values("Sales", ascending=False)
)

# Display the category-wise Sales and Profit
print(category_summary)

                       Sales       Profit
Category
Technology       836154.0330  145454.9481
Furniture        741999.7953   18451.2728
Office Supplies  719047.0320  122490.8008

In [38]:
# Rank regions by their total Profit
# This helps us identify which geographic region contributes the most profit

region_profit = (
    df.groupby("Region")["Profit"]
    .sum()
    .sort_values(ascending=False)
)

print(region_profit)

Region
West       108418.4489
East        91522.7800
South       46749.4303
Central     39706.3625
Name: Profit, dtype: float64

In [39]:
# Rank all regions by their total Profit
# This helps us identify which geographic region contributes the most
# profit to the overall business

region_profit = (
    df.groupby("Region")["Profit"]
    .sum()
    .sort_values(ascending=False)
)

print(region_profit)

Region
West       108418.4489
East        91522.7800
South       46749.4303
Central     39706.3625
Name: Profit, dtype: float64

In [40]:
# Calculate total Sales and Profit for each sub-category
# This gives us a more detailed view of which product groups
# are performing strongly or poorly within each major category

subcategory_metrics = (
    df.groupby("Sub-Category")[["Sales", "Profit"]]
    .sum()
    .sort_values("Profit", ascending=False)
)

# Display all sub-categories ranked from highest to lowest profit
print(subcategory_metrics)

                    Sales      Profit
Sub-Category
Copiers       149528.0300  55617.8249
Phones        330007.0540  44515.7306
Accessories   167380.3180  41936.6357
Paper          78479.2060  34053.5693
Binders       203412.7330  30221.7633
Chairs        328449.1030  26590.1663
Storage       223843.6080  21278.8264
Appliances    107532.1610  18138.0054
Furnishings    91705.1640  13059.1436
Envelopes      16476.4020   6964.1767
Art            27118.7920   6527.7870
Labels         12486.3120   5546.2540
Machines      189238.6310   3384.7569
Fasteners       3024.2800    949.5182
Supplies       46673.5380  -1189.0995
Bookcases     114879.9963  -3472.5560
Tables        206965.5320 -17725.4811

In [41]:
# Calculate total Sales and Profit for each sub-category
# We need both values to determine how efficiently each sub-category
# converts its Sales into Profit

subcategory_margin = (
    df.groupby("Sub-Category")[["Sales", "Profit"]]
    .sum()
)

# Calculate Profit Margin as a percentage of Sales
# A higher percentage means the sub-category keeps more of its
# revenue as profit

subcategory_margin["Profit Margin (%)"] = (
    subcategory_margin["Profit"] / subcategory_margin["Sales"]
) * 100

# Rank sub-categories from highest to lowest profit margin
# This helps us identify the most efficient product groups

subcategory_margin = subcategory_margin.sort_values(
    "Profit Margin (%)",
    ascending=False
)

print(subcategory_margin)

                    Sales      Profit  Profit Margin (%)
Sub-Category
Labels         12486.3120   5546.2540          44.418672
Paper          78479.2060  34053.5693          43.391837
Envelopes      16476.4020   6964.1767          42.267582
Copiers       149528.0300  55617.8249          37.195585
Fasteners       3024.2800    949.5182          31.396504
Accessories   167380.3180  41936.6357          25.054700
Art            27118.7920   6527.7870          24.071083
Appliances    107532.1610  18138.0054          16.867517
Binders       203412.7330  30221.7633          14.857361
Furnishings    91705.1640  13059.1436          14.240358
Phones        330007.0540  44515.7306          13.489327
Storage       223843.6080  21278.8264           9.506113
Chairs        328449.1030  26590.1663           8.095673
Machines      189238.6310   3384.7569           1.788618
Supplies       46673.5380  -1189.0995          -2.547695
Bookcases     114879.9963  -3472.5560          -3.022768
Tables        206965.5320 -17725.4811          -8.564460

In [42]:
# Filter the sub-categories where total Profit is negative
# These are product groups that lose money overall
# and therefore deserve business attention

loss_making_subcategories = subcategory_metrics[
    subcategory_metrics["Profit"] < 0
].sort_values("Profit")

# Display the loss-making sub-categories
print(loss_making_subcategories)

                    Sales      Profit
Sub-Category
Tables        206965.5320 -17725.4811
Bookcases     114879.9963  -3472.5560
Supplies       46673.5380  -1189.0995

In [43]:
# Calculate total Sales and Profit for each region
# We need both values so we can measure how profitable each region is

regional_summary = (
    df.groupby("Region")[["Sales", "Profit"]]
    .sum()
)

# Calculate Profit Margin for each region
# This tells us what percentage of Sales is converted into Profit

regional_summary["Profit Margin (%)"] = (
    regional_summary["Profit"] / regional_summary["Sales"]
) * 100

# Sort regions by Profit Margin from highest to lowest
# This makes it easy to identify the most and least efficient regions

regional_summary = regional_summary.sort_values(
    "Profit Margin (%)",
    ascending=False
)

print(regional_summary)

               Sales       Profit  Profit Margin (%)
Region
West     725457.8245  108418.4489          14.944831
East     678781.2400   91522.7800          13.483399
South    391721.9050   46749.4303          11.934342
Central  501239.8908   39706.3625           7.921629

In [44]:
# Save our current DataFrame as a new CSV file
# This creates a dashboard-ready copy while keeping the original
# Superstore dataset unchanged

df.to_csv("../data/superstore_cleaned.csv", index=False)

# Confirm that the cleaned dataset was saved successfully
print("Cleaned dataset saved successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Cleaned dataset saved successfully!
Rows: 9994
Columns: 23

In [45]:
# Calculate the profit margin for each product category
# Profit margin shows how much profit is generated from every unit of sales

category_margin = (
    df.groupby("Category")
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum")
    )
)

# Calculate profit margin as a percentage
category_margin["Profit Margin"] = (
    category_margin["Profit"] / category_margin["Sales"] * 100
)

# Sort categories from highest to lowest profit margin
category_margin = category_margin.sort_values(
    "Profit Margin",
    ascending=False
)

# Display the category-wise sales, profit, and profit margin
print(category_margin)

                       Sales       Profit  Profit Margin
Category
Technology       836154.0330  145454.9481      17.395712
Office Supplies  719047.0320  122490.8008      17.035158
Furniture        741999.7953   18451.2728       2.486695